### ISSUE TITLE
Doesn't work in servers

### ISSUE THREAD

**Issue by rsmyst** [An00nymushun/DiscordFreeStickers#10]
all stickers are accessible while private dming
but no external stickers if i'm on another server. is this not fixable?

**Comment by An00nymushun** [comment]
You did not follow the issue template.
I'm pretty sure the server you are trying to use it in, simply disallowed you from using external stickers.
This plugin isn't made to get around that.
Or possibly you are not allowed to upload attachments.

**Comment by rsmyst** [comment]
> You did not follow the issue template. I'm pretty sure the server you are trying to use it in, simply disallowed you from using external stickers. This plugin isn't made to get around that. Or possibly you are not allowed to upload attachments.

Oh i didn't think about that. My bad, that was probably the case. i don't think i have attachment perms.
