### ISSUE TITLE
Not working in the new version?

### ISSUE THREAD

**Issue by MatheusPoliCamilo** [An00nymushun/DiscordFreeStickers#13]
**Describe the bug**
It isn't working on Discord new version.

**To Reproduce**
Using the emoji picker, now appears a message informing that can't use the emoji.
![image](https://user-images.githubusercontent.com/25781749/162856573-93418f4a-e15c-443a-995f-634dfcb0334c.png)

**Client:**
 - Desktop Windows 10 64-Bit (10.0.22000)
 - Discord Build Channel Release
 - Plugin Version 1.4
 - BD Version 1.5.3

**Comment by Korosys** [comment]
also having this issue

**Comment by An00nymushun** [comment]
This repository is DiscordFreeStickers, not DiscordFreeEmojis, the newest version of DiscordFreeEmojis is 1.6

**Comment by rastafaa** [comment]
He fixed it!! :D

**Comment by Einhornyordle** [comment]
Still not working for me.
![Untitled](https://user-images.githubusercontent.com/47315090/167200981-06534de8-504c-4ec3-9b01-ee3dc9bae08d.png)

Canary 127161 (2319539)
BetterDiscord 1.5.3
Host 0.0.135 Linux 64-Bit (5.4.0-109-Generic)
