### ISSUE TITLE
Animated stickers not working

### ISSUE THREAD

**Issue by nekohan69** [An00nymushun/DiscordFreeStickers#17]
**Describe the bug**
After clicking the animated stickers it send clientsided stickers and its not a link of a gif, its like you having nitro and casually send a stickers, if there are new messages the stickers deleted automatically.

**Screenshots**
https://ibb.co/VDkGRYC
https://ibb.co/JdP2Jvz

**Comment by An00nymushun** [comment]
Did you try with different stickers too, and in different channels?
Check the devtools console for errors and also try disabling all other plugins.

**Comment by nekohan69** [comment]
I think I found the problem here, it worked after i disabled SplitLargeFile plugin. My bad for not trying disabling all plugins. Thank you!

**Comment by l-Nuril-l** [comment]
@An00nymushun Could you try making them compatible?
![image](https://user-images.githubusercontent.com/49325887/175203522-13d78142-b3bf-4b2e-9cac-722b317b7426.png)

**Comment by An00nymushun** [comment]
> @An00nymushun Could you try making them compatible? ![image](https://user-images.githubusercontent.com/49325887/175203522-13d78142-b3bf-4b2e-9cac-722b317b7426.png)

@l-Nuril-l 
The upload hook in SplitLargeFiles is outdated, but it doesn't cause issues because discord rarely uses that upload method nowadays, but I use it.
The arguments should be in an object.
