### ISSUE TITLE
Non Animated Stickers nor The Animated Stickers are working please help

### ISSUE THREAD

**Issue by TheWeebSamurai** [An00nymushun/DiscordFreeStickers#22]
Its not working for me. Are there any dependencies or any library required for it to work? Like ZeresPLuginLibrary?

Its showing `Your message could not be delivered. This is usually because you don't share a server with the recipient or the recipient is only accepting direct messages from friends.`. What to do please help

**Comment by An00nymushun** [comment]
There are no required libraries.
Please follow the issue template.
