### ISSUE TITLE
sends 2 sitickers

### ISSUE THREAD

**Issue by AwakeSoda** [An00nymushun/DiscordFreeStickers#5]
![image](https://user-images.githubusercontent.com/51978082/141759885-a818828e-718f-415b-a5d0-e84e04e69512.png)
as you can see it sends a real sticker and a gif of one

**Comment by An00nymushun** [comment]
Do you get any error messages in the Ctrl-Shift-I console?

**Comment by AwakeSoda** [comment]
> Do you get any error messages in the Ctrl-Shift-I console?

![image](https://user-images.githubusercontent.com/51978082/142290977-fbe2aba7-8956-4f70-940a-f7ba8dcde44c.png)

**Comment by An00nymushun** [comment]
That's unrelated, look for something else
