### ISSUE TITLE
discord gives Your message could not be delivered. This is usually because you don't share a server with the recipient or the recipient is only accepting direct messages from friends. You can see the full list of reasons here: https://support.discord.com/hc/en-us/articles/360060145013 .

### ISSUE THREAD

**Issue by redbluexe1** [An00nymushun/DiscordFreeStickers#6]
this happened. even on a community server. how.

**Comment by redbluexe1** [comment]
![image](https://user-images.githubusercontent.com/86514546/142131736-f3f1acdb-70db-440a-97ad-107e85799ae6.png)

**Comment by redbluexe1** [comment]
that sticker is from my server btw

**Comment by An00nymushun** [comment]
Do you have attach files permissions? Aka can you send files in that channel?

**Comment by redbluexe1** [comment]
> Do you have attach files permissions? Aka can you send files in that channel?

yes. and i tried on the dms and the same thing

**Comment by An00nymushun** [comment]
Any errors in the Ctrl-Shift-I console?

**Comment by redbluexe1** [comment]
> Any errors in the Ctrl-Shift-I console?

discord app. its in a discord app

**Comment by redbluexe1** [comment]
nvm it fixed itself
