### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by Baonamtranpro432011** [An00nymushun/DiscordFreeStickers#7]
It's like this:
![image](https://user-images.githubusercontent.com/93915498/143667968-c051e414-f32a-4f2b-9927-99550c01580c.png)
![image](https://user-images.githubusercontent.com/93915498/143667975-a5983e71-6b7e-4f53-9f59-6f2ebb87a55c.png)

**Comment by Baonamtranpro432011** [comment]
help

**Comment by Baonamtranpro432011** [comment]
help pls

**Comment by An00nymushun** [comment]
Okay stop spamming

Check Ctrl-Shift-I console for errors, also turn off all the other plugins and restart discord

**Comment by Baonamtranpro432011** [comment]
thk

**Comment by Baonamtranpro432011** [comment]
working now

**Comment by Baonamtranpro432011** [comment]
is your plugin work on canary?

**Comment by An00nymushun** [comment]
I don't know, I mainly use the normal version.

**Comment by Baonamtranpro432011** [comment]
...

**Comment by Baonamtranpro432011** [comment]
now is back to normal

**Comment by Baonamtranpro432011** [comment]
not working
