### ISSUE TITLE
DiscordFreeStickers doesn't load

### ISSUE THREAD

**Issue by orowith2os** [An00nymushun/DiscordFreeStickers#8]
I've tried copying the code directly to the folder, and it always happens, it doesn't load the plugin. I'm thinking it's a typo or a misclick somewhere in the code, since most of it is shown in red in Kate. Image attached. If there's anything else you need me to show, I'll be happy to send it. 
![image](https://user-images.githubusercontent.com/93224879/143735788-5f28b9bc-3e5a-4eae-b373-86e819417b4c.png)
![image](https://user-images.githubusercontent.com/93224879/143735802-dba98e91-d7ec-44c0-88ad-b96926a0881a.png)

**Comment by An00nymushun** [comment]
The plugin is simply too big to copy-paste, you need to download it properly.
This happened to me too.

The red part is just because it's a big string.

**Comment by orowith2os** [comment]
This works, thanks! For anybody looking back on this: I clicked on the green "Code" button and "Download ZIP"
