### ISSUE TITLE
Crashes Discord when pressing the Stickers Button on powercord

### ISSUE THREAD

**Issue by PeterStrick** [An00nymushun/DiscordFreeStickers#9]
The Plugin crashes Discord entirely upon pressing the Stickers button, when using Powercord.

**OS:** Windows 8.1 x64
**Discord Canary Version:** 107393 (d1677d6)
**Powercord Revision | Branch:** [1d2318b](https://github.com/powercord-org/powercord/tree/1d2318bcd7c5e5a5230d8bf25813ed648cfd7b76) (latest) | v2
**bdCompat Version:** [v0.3.10](https://github.com/Juby210/bdCompat/tree/d758d7fbed95c37b6921244c1215727f2ac4ddef)
**DiscordFreeStickers Version:** v1.1

**Error in Console:**
![image](https://user-images.githubusercontent.com/60312421/145214498-6d6b6fba-3e61-40a2-9d35-ead8b43659b6.png)
![image](https://user-images.githubusercontent.com/60312421/145214612-bcfe8641-9a1d-4bd2-a111-8e0d7c45013d.png)

**Comment by An00nymushun** [comment]
I'm pretty sure it's an issue with bdCompat https://github.com/Juby210/bdCompat/blob/d758d7fbed95c37b6921244c1215727f2ac4ddef/modules/Patcher.js#L74
It should pass callOriginalMethod instead of returnValue if it's an instead hook.

Why not just use BD?

**Comment by PeterStrick** [comment]
> I'm pretty sure it's an issue with bdCompat https://github.com/Juby210/bdCompat/blob/d758d7fbed95c37b6921244c1215727f2ac4ddef/modules/Patcher.js#L74 It should pass callOriginalMethod instead of returnValue if it's an instead hook.
> 
> Why not just use BD?

Eh it´s personal preference. Also thought that it would work fine under Powercord, because your Free Emoji Plugin does.

**Comment by An00nymushun** [comment]
The Free Emojis plugin works, but powercord people will literally harass you on their server if they find out you are using it.

**Comment by PeterStrick** [comment]
> but powercord people will literally harass you on their server if they find out you are using it.

Good to know
